cache:
  paths:
    - /root/.m2/repository
stages:
  - build
  - deploy
build-job:
  stage: build
  image: maven:3.6.2-jdk-11
  script:
    - mvn clean package -DskipTests
  tags:
    - docker
deploy-job:
  stage: deploy
  image: ruby:2.4
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APPNAME  --api-key=$HEROKU_APIKEY
  environment:
    name: dev
    url: $HEROKU_APPHOST
  only:
    - master
  tags:
    - docker

